### ISSUE TITLE
How to get rid of the transparent background grid?

### ISSUE THREAD

**Issue by isaacdarcilla** [cyntler/react-doc-viewer#179]
How to get rid of the transparent background grid? Basically remove it?

![image](https://github.com/cyntler/react-doc-viewer/assets/22732118/90838a7c-3f09-4f16-9057-bba1900a7802)

**Comment by isaacdarcilla** [comment]
Fixed: 

Just override the styles

```css
#image-renderer {
    display: flex;
    flex: 1;
    align-items: start;
    justify-content: start;
    width: 100%;
    height: 100%;
    background-color: transparent;
}

#react-doc-viewer {
    display: inline-block;
    flex-direction: column;
    overflow: hidden;
    background: white;
    width: auto;
    height: auto;
}

#image-img {
    max-width: 100%;
    max-height: 100%;
}

```
