### ISSUE TITLE
`mainState` prop on a DOM element.

### ISSUE THREAD

**Issue by tomfranciseu** [cyntler/react-doc-viewer#214]
On initial loading of an image / pdf / ...
**Warning:** React does not recognize the `mainState` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `mainstate` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

It seems to be related to this code: 
const ImageProxyRenderer: DocRenderer = (props) => {
  const {
    mainState: { currentDocument },
    children,
  } = props;

  if (!currentDocument) return null;

  return (
    <Container id="image-renderer" {...props}>
      {children || (
        <Img id="image-img" src={currentDocument.fileData as string} />
      )}
    </Container>
  );
};
Where passinng mainstate to styledcomponents (container & img) is not allowed.

**Comment by magnattic** [comment]
Workaround (not great, but better than nothing):

Wrap your code/app in this provider:

```
import { StyleSheetManager } from 'styled-components'

<StyleSheetManager shouldForwardProp={(prop) => prop !== 'mainState'}>
...
</StyleSheetManager>
```

If you don't have styled-components, install it. 
Attention: Make sure you don't have multiple versions of the same 'styled-components' package. If you are using yarn pnp, use `yarn why styled-components` to check and `yarn dedupe styled-components` to fix.

**Comment by magnattic** [comment]
I just realized that this actually breaks the default PNG renderer, which relies on the mainState to be forwarded implicitely. :(

**Comment by ilomon10** [comment]
just made custom PNGRenderer

```ts
// ./png-renderer.ts
import React from "react";
import { DocRenderer } from "@cyntler/react-doc-viewer";
import "@/styles/png-renderer.css";

const PNGRenderer: DocRenderer = (props) => {
  const document = props.mainState.currentDocument;
  if (!document) return null;
  return (
    <div id="png-renderer">
      <img src={document.fileData as string} />
    </div>
  );
};

PNGRenderer.fileTypes = ["png", "image/png"];
PNGRenderer.weight = 0;

export default PNGRenderer;
```

then copy the style from https://github.com/cyntler/react-doc-viewer/blob/main/src/renderers/png/index.tsx

```css
#png-renderer {
  display: flex;
  flex: 1 1 0%;
  align-items: center;
  justify-content: center;
  height: 100%;
  background-color: white;
  background-image: 
    linear-gradient(45deg, rgb(224, 224, 224) 25%, transparent 25%),
    linear-gradient(-45deg, rgb(224, 224, 224) 25%, transparent 25%),
    linear-gradient(45deg, transparent 75%, rgb(224, 224, 224) 75%), 
    linear-gradient(-45deg, transparent 75%, rgb(224, 224, 224) 75%);
  background-size: 20px 20px;
  background-position: 0px 0px, 0px 10px, 10px -10px, -10px 0px;
}

```
