### ISSUE TITLE
Doc viewer height not being adjusted

### ISSUE THREAD

**Issue by khaledgaaieb** [cyntler/react-doc-viewer#310]
the height is not being update even when using the following code: 

```
 <DocViewer
        documents={docs}
        pluginRenderers={DocViewerRenderers}
        style={{ height: "1000", width: "100%" }}
        config={{ header: { disableHeader: true } }}
      />
```

![Image](https://github.com/user-attachments/assets/98b11a60-e7bf-4040-95a4-9e543c8e00e9)

**Comment by nirmitsaini1024** [comment]
+1 
please fix this as soon as possible.

**Comment by nirmitsaini1024** [comment]
> [https://view.officeapps.live.com/op/embed.aspx?src=${url_to_your_doc}](https://view.officeapps.live.com/op/embed.aspx?src=$%7Burl_to_your_doc%7D)
> 
> I ended up using view from officeapps

Thanks for the reply, also after embedding it, is there any way to search using a custom search bar and highlight the word in the viewer in brower. just like it does in pdf viewer locally.

**Comment by JosephScript** [comment]
I ended up using:

```css
#msdoc-renderer {
    height: 100vh;
  }
```

**Comment by Exclusiveideas** [comment]
.react-doc-viewer .fBdFME {
  height: 100% !important;
}

**Comment by jayesh96** [comment]
Added a custom container class

.chat-preview-wrapper {
  height: 100%;

  #proxy-renderer {
    height: 100%;
  }

  #msdoc-renderer {
    height: 100%;
  }
}

**Comment by velrino** [comment]
Wrap the `DocViewer` in a container with a fixed height and override the internal element heights via CSS:

```css
.doc-viewer-wrapper {
  height: 100%;
}

.doc-viewer-wrapper #react-doc-viewer,
.doc-viewer-wrapper #react-doc-viewer > div,
.doc-viewer-wrapper #proxy-renderer,
.doc-viewer-wrapper #msdoc-renderer,
.doc-viewer-wrapper #msdoc-iframe {
  height: 100% !important;
  overflow: auto;
}
```

```jsx
<div className="doc-viewer-wrapper" style={{ height: '70vh' }}>
  <DocViewer
    documents={docs}
    pluginRenderers={DocViewerRenderers}
    style={{ height: '100%' }}
    config={{ header: { disableHeader: true } }}
  />
</div>
```
